name: Apply incoming bundle and open PR

on:
  push:
    branches: ['**']          # any branch (incl. v2.0)
    paths: ['incoming/**']
  workflow_dispatch:
    inputs:
      file:
        description: 'incoming/<file>.zip or .patch'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug context
        shell: bash
        run: |
          echo "Event:  $GITHUB_EVENT_NAME"
          echo "Ref:    $GITHUB_REF  (branch: ${GITHUB_REF##*/})"
          echo "SHA:    $GITHUB_SHA"
          echo "Input:  '${{ inputs.file }}'"
          echo "incoming/:"
          ls -l incoming || true

      - name: Determine payload file
        id: pick
        shell: bash
        run: |
          set -euo pipefail
          CANDIDATE="${{ inputs.file }}"
          if [[ -z "$CANDIDATE" ]]; then
            if git diff-tree --no-commit-id --name-only -r "$GITHUB_SHA" | grep -q '^incoming/'; then
              CANDIDATE=$(git diff-tree --no-commit-id --name-only -r "$GITHUB_SHA" \
                | grep '^incoming/' | grep -Ei '\.(zip|patch)$' | head -n1 || true)
            fi
            if [[ -z "${CANDIDATE:-}" ]]; then
              CANDIDATE=$(ls -t incoming/*.{zip,ZIP,patch,PATCH} 2>/dev/null | head -n1 || true)
            fi
          fi
          echo "Candidate: $CANDIDATE"
          echo "file=${CANDIDATE:-}" >> "$GITHUB_OUTPUT"

      - name: Stop if no candidate
        if: steps.pick.outputs.file == ''
        shell: bash
        run: |
          echo "No .zip or .patch found in incoming/. Provide inputs.file or push a file to incoming/."
          exit 0

      - name: Apply payload
        if: steps.pick.outputs.file != ''
        id: apply
        shell: bash
        run: |
          set -euo pipefail
          FILE="${{ steps.pick.outputs.file }}"
          echo "Applying: $FILE"
          if [[ ! -f "$FILE" ]]; then
            echo "::error::File not found: $FILE"
            exit 1
          fi

          mkdir -p _work/apply

          if [[ "$FILE" =~ \.zip$|\.ZIP$ ]]; then
            unzip -o "$FILE" -d _work/apply
            echo "Bundle contents (top 2 levels):"
            find _work/apply -maxdepth 2 -type f -print

            FIXROOT=$(find _work/apply -type d -path "*/the-grey-fixes" | head -n1 || true)
            if [[ -n "${FIXROOT:-}" ]]; then
              echo "Fix root: $FIXROOT"
              if [[ -f "$FIXROOT/apply_the_grey_fixes.sh" ]]; then
                echo "Running helper script…"
                bash "$FIXROOT/apply_the_grey_fixes.sh"
              else
                echo "No helper script; copying from fix root."
                rsync -a --exclude 'incoming/' "$FIXROOT"/ ./
              fi
            else
              echo "No the-grey-fixes/ dir; copying whole payload."
              rsync -a --exclude 'incoming/' _work/apply/ ./
            fi

          elif [[ "$FILE" =~ \.patch$|\.PATCH$ ]]; then
            echo "Applying patch…"
            git apply --index "$FILE"
          else
            echo "::error::Unsupported file type: $FILE"
            exit 1
          fi

          git reset incoming || true
          git add -A || true

          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.apply.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ github.ref_name }}
          branch: bot/apply-incoming-${{ github.run_id }}
          delete-branch: true
          title: "bot: apply incoming payload"
          body: |
            Automatically applied `${{ steps.pick.outputs.file }}` on `${{ github.ref_name }}`.
            Review the diff; backups may appear as *.bak.
          commit-message: "bot: apply ${{ steps.pick.outputs.file }}"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: No changes (info)
        if: steps.apply.outputs.changed != 'true'
        shell: bash
        run: echo "No changes detected; nothing to PR."
