      - name: Apply payload
        id: apply
        shell: bash
        run: |
          set -euo pipefail
          FILE="${{ steps.pick.outputs.file }}"
          echo "Applying: $FILE"
          mkdir -p _work/apply

          if [[ "$FILE" =~ \.zip$|\.ZIP$ ]]; then
            unzip -o "$FILE" -d _work/apply
            echo "Bundle contents:"
            find _work/apply -maxdepth 2 -type f -print

            # ✅ RUN helper if it exists (don't require +x on the file)
            if [[ -f "_work/apply/the-grey-fixes/apply_the_grey_fixes.sh" ]]; then
              echo "Running helper script…"
              bash "_work/apply/the-grey-fixes/apply_the_grey_fixes.sh"
            else
              echo "No helper script; copying bundle contents."
              rsync -a --exclude 'incoming/' _work/apply/ ./
            fi

          elif [[ "$FILE" =~ \.patch$|\.PATCH$ ]]; then
            git apply --index "$FILE"
          else
            echo "Unsupported file type: $FILE"
            exit 1
          fi

          git reset incoming || true
          git add -A || true

          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
